apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: business-exchange-auction
  annotations:
    run.googleapis.com/ingress: all
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "5"
        autoscaling.knative.dev/minScale: "0"
        run.googleapis.com/execution-environment: gen2
    spec:
      containerConcurrency: 100
      timeoutSeconds: 900
      containers:
      - image: gcr.io/businessexchange-468413/business-exchange-auction:latest
        ports:
        - name: http1
          containerPort: 8080
        env:
        - name: APP_ENV
          value: "production"
        - name: DB_HOST
          value: "localhost"
        - name: DB_PORT
          value: "3306"
        - name: DB_USER
          value: "root"
        - name: DB_PASSWORD
          value: "password"
        - name: DB_NAME
          value: "business_exchange"
        - name: REDIS_HOST
          value: "localhost:6379"
        - name: JWT_SECRET
          value: "test-jwt-secret"
        - name: CORS_ALLOWED_ORIGINS
          value: "*"
        resources:
          limits:
            cpu: "1"
            memory: "1Gi"
          requests:
            cpu: "0.5"
            memory: "256Mi"
        # 暫時移除健康檢查以測試基本啟動