apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: auction-service
  annotations:
    run.googleapis.com/ingress: all
    run.googleapis.com/execution-environment: gen2
spec:
  template:
    metadata:
      annotations:
        autoscaling.knative.dev/maxScale: "10"
        autoscaling.knative.dev/minScale: "1"
        run.googleapis.com/cpu-throttling: "false"
        run.googleapis.com/execution-environment: gen2
    spec:
      serviceAccountName: auction-service-sa
      containerConcurrency: 100
      timeoutSeconds: 300
      containers:
      - image: gcr.io/PROJECT_ID/auction-service:latest
        ports:
        - name: http1
          containerPort: 8081
        env:
        - name: APP_ENV
          value: "production"
        - name: APP_PORT
          value: "8081"
        - name: DB_HOST
          valueFrom:
            secretKeyRef:
              name: auction-db-config
              key: host
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: auction-db-config
              key: user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: auction-db-config
              key: password
        - name: DB_NAME
          valueFrom:
            secretKeyRef:
              name: auction-db-config
              key: database
        - name: REDIS_HOST
          valueFrom:
            secretKeyRef:
              name: auction-redis-config
              key: host
        - name: JWT_SECRET
          valueFrom:
            secretKeyRef:
              name: auction-jwt-config
              key: secret
        resources:
          limits:
            cpu: "2"
            memory: "2Gi"
          requests:
            cpu: "1"
            memory: "512Mi"
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /healthz
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 10