version: '3.8'

services:
  auction-service:
    build: .
    ports:
      - "8081:8081"
    environment:
      - APP_ENV=production
      - APP_PORT=8081
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=auction_user
      - DB_PASSWORD=auction_password
      - DB_NAME=business_exchange_marketplace
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - JWT_SECRET=${JWT_SECRET:-your-jwt-secret-key}
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8081/healthz"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root_password
      MYSQL_DATABASE: business_exchange_marketplace
      MYSQL_USER: auction_user
      MYSQL_PASSWORD: auction_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 3

  # 定時任務：拍賣結束作業
  finalize-job:
    build: .
    command: ./finalize-job
    environment:
      - APP_ENV=production
      - DB_HOST=mysql
      - DB_PORT=3306
      - DB_USER=auction_user
      - DB_PASSWORD=auction_password
      - DB_NAME=business_exchange_marketplace
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: "no"
    profiles:
      - job

volumes:
  mysql_data:
  redis_data: